-- local raptors = {}

-- for key, _ in pairs(UnitDefs) do
--     if string.sub(key, 1, 6) == "raptor" then
--         table.insert(raptors, key)
--     end
-- end

raptors = {
    "raptor_6legged_l",
    "raptor_air_bomber_acid_t2_v1",
    "raptor_air_bomber_basic_t1_v1",
    "raptor_air_bomber_basic_t2_v1",
    "raptor_air_bomber_basic_t2_v2",
    "raptor_air_bomber_basic_t4_v1",
    "raptor_air_bomber_basic_t4_v2",
    "raptor_air_bomber_brood_t4_v2",
    "raptor_air_bomber_brood_t4_v3",
    "raptor_air_bomber_brood_t4_v4",
    "raptor_air_bomber_emp_t2_v1",
    "raptor_air_fighter_basic_t1_v1",
    "raptor_air_fighter_basic_t2_v1",
    "raptor_air_fighter_basic_t2_v2",
    "raptor_air_fighter_basic_t2_v3",
    "raptor_air_fighter_basic_t2_v4",
    "raptor_air_fighter_basic_t4_v1",
    "raptor_air_gunship_acid_t2_v1",
    "raptor_air_gunship_antiair_t2_v1",
    "raptor_air_gunship_basic_t2_v1",
    "raptor_air_gunship_emp_t2_v1",
    "raptor_air_gunship_fire_t2_v1",
    "raptor_air_kamikaze_basic_t2_v1",
    "raptor_air_scout_basic_t2_v1",
    "raptor_air_scout_basic_t3_v1",
    "raptor_air_scout_basic_t4_v1",
    "raptor_allterrain_arty_acid_t2_v1",
    "raptor_allterrain_arty_acid_t4_v1",
    "raptor_allterrain_arty_basic_t2_v1",
    "raptor_allterrain_arty_basic_t4_v1",
    "raptor_allterrain_arty_brood_t2_v1",
    "raptor_allterrain_arty_brood_t4_v1",
    "raptor_allterrain_arty_emp_t2_v1",
    "raptor_allterrain_arty_emp_t4_v1",
    "raptor_allterrain_assault_acid_t2_v1",
    "raptor_allterrain_assault_basic_t2_v1",
    "raptor_allterrain_assault_basic_t2_v2",
    "raptor_allterrain_assault_basic_t2_v3",
    "raptor_allterrain_assault_basic_t4_v1",
    "raptor_allterrain_assault_basic_t4_v2",
    "raptor_allterrain_assault_emp_t2_v1",
    "raptor_allterrain_swarmer_acid_t2_v1",
    "raptor_allterrain_swarmer_basic_t2_v1",
    "raptor_allterrain_swarmer_basic_t3_v1",
    "raptor_allterrain_swarmer_basic_t4_v1",
    "raptor_allterrain_swarmer_emp_t2_v1",
    "raptor_allterrain_swarmer_fire_t2_v1",
    "raptor_antinuke",
    "raptor_hive",
    "raptor_land_assault_acid_t2_v1",
    "raptor_land_assault_basic_t2_v1",
    "raptor_land_assault_basic_t2_v2",
    "raptor_land_assault_basic_t2_v3",
    "raptor_land_assault_basic_t4_v1",
    "raptor_land_assault_basic_t4_v2",
    "raptor_land_assault_emp_t2_v1",
    "raptor_land_assault_spectre_t2_v1",
    "raptor_land_assault_spectre_t4_v1",
    "raptor_land_kamikaze_basic_t2_v1",
    "raptor_land_kamikaze_basic_t4_v1",
    "raptor_land_kamikaze_emp_t2_v1",
    "raptor_land_kamikaze_emp_t4_v1",
    "raptor_land_spiker_basic_t2_v1",
    "raptor_land_spiker_basic_t4_v1",
    "raptor_land_spiker_spectre_t4_v1",
    "raptor_land_swarmer_acids_t2_v1",
    "raptor_land_swarmer_basic_t1_v1",
    "raptor_land_swarmer_basic_t2_v1",
    "raptor_land_swarmer_basic_t2_v2",
    "raptor_land_swarmer_basic_t2_v3",
    "raptor_land_swarmer_basic_t2_v4",
    "raptor_land_swarmer_basic_t3_v1",
    "raptor_land_swarmer_basic_t3_v2",
    "raptor_land_swarmer_basic_t3_v3",
    "raptor_land_swarmer_basic_t4_v1",
    "raptor_land_swarmer_basic_t4_v2",
    "raptor_land_swarmer_brood_t2_v1",
    "raptor_land_swarmer_brood_t3_v1",
    "raptor_land_swarmer_brood_t4_v1",
    "raptor_land_swarmer_emp_t2_v1",
    "raptor_land_swarmer_fire_t2_v1",
    "raptor_land_swarmer_fire_t4_v1",
    "raptor_land_swarmer_heal_t1_v1",
    "raptor_land_swarmer_heal_t2_v1",
    "raptor_land_swarmer_heal_t3_v1",
    "raptor_land_swarmer_heal_t4_v1",
    "raptor_land_swarmer_spectre_t3_v1",
    "raptor_land_swarmer_spectre_t4_v1",
    "raptor_matriarch_acid",
    "raptor_matriarch_basic",
    "raptor_matriarch_electric",
    "raptor_matriarch_fire",
    "raptor_matriarch_healer",
    "raptor_matriarch_spectre",
    "raptor_queen_easy",
    "raptor_queen_epic",
    "raptor_queen_hard",
    "raptor_queen_normal",
    "raptor_queen_veryeasy",
    "raptor_queen_veryhard",
    "raptor_turret_acid_t2_v1",
    "raptor_turret_acid_t3_v1",
    "raptor_turret_acid_t4_v1",
    "raptor_turret_antiair_t2_v1",
    "raptor_turret_antiair_t3_v1",
    "raptor_turret_antiair_t4_v1",
    "raptor_turret_antinuke_t2_v1",
    "raptor_turret_antinuke_t3_v1",
    "raptor_turret_basic_t2_v1",
    "raptor_turret_basic_t3_v1",
    "raptor_turret_basic_t4_v1",
    "raptor_turret_burrow_t2_v1",
    "raptor_turret_emp_t2_v1",
    "raptor_turret_emp_t3_v1",
    "raptor_turret_emp_t4_v1",
    "raptor_turret_meteor_t4_v1",
    "raptor_worm_green",
    "raptorartillery",
    "raptorh1b",
    "raptorh5",
}


local hive = UnitDefs["armhavp"]
local com = UnitDefs["raptorh5"]

com.canattack = false
com.canrepair = true
com.canreclaim = true
com.canrestore = true

for index, raptor in ipairs(raptors) do
    hive.buildoptions[index] = raptor
    com.buildoptions[index] = raptor
end

local armcom = UnitDefs["armcom"]

armcom.buildoptions[#armcom.buildoptions + 1] = "armhavp"
